name: Close Issue and Delete Branch on Merge to Develop

on:
    pull_request:
        types:
            - closed

jobs:
    close-issue-and-delete-branch:
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Close related issues
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                BRANCH_NAME=${{ github.event.pull_request.head.ref }}
                echo "BRANCH_NAME: $BRANCH_NAME"
                # Extract issue number from branch name (assuming branch name is like feature-issue#123)
                ISSUE_NUMBER=$(echo "$BRANCH_NAME" | grep -Eo 'feature-issue#[0-9]+' | grep -Eo '[0-9]+')
                echo "ISSUE_NUMBER: $ISSUE_NUMBER"
                if [[ "$ISSUE_NUMBER" != "" ]]; then
                  gh issue edit $ISSUE_NUMBER --state closed
                fi

            - name: Delete branch
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                BRANCH_NAME=${{ github.event.pull_request.head.ref }}
                echo "BRANCH_NAME: $BRANCH_NAME"
                if [[ "$BRANCH_NAME" != "" && "$BRANCH_NAME" != "develop" && "$BRANCH_NAME" != "master" ]]; then
                  git push origin --delete $BRANCH_NAME
                fi