name: Close Issue and Delete Branch on Merge to Develop

on:
    pull_request:
        types:
            - closed

jobs:
    close-issue-and-delete-branch:
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/github/super-linter:latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Close related issues
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                PR_NUMBER=${{ github.event.pull_request.number }}
                echo "PR_NUMBER----------------- $PR_NUMBER"
                ISSUE_BODY=$(gh pr view $PR_NUMBER --json body --jq ".body")
                echo "ISSUE_BODY----------------- $ISSUE_BODY"
                ISSUE_NUMBER=$(echo "$ISSUE_BODY" | grep -oP "(?<=Closes #)\d+")
                echo "ISSUE_NUMBER----------------- $ISSUE_NUMBER"
                if [[ "$ISSUE_NUMBER" != "" ]]; then
                  gh issue edit $ISSUE_NUMBER --state closed
                fi

            - name: Delete branch
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                BRANCH_NAME=${{ github.event.pull_request.head.ref }}
                echo "BRANCH_NAME----------------- $BRANCH_NAME"
                if [[ "$BRANCH_NAME" != "" && "$BRANCH_NAME" != "develop" && "$BRANCH_NAME" != "master" ]]; then
                  git push origin --delete $BRANCH_NAME
                fi